### ISSUE TITLE
Is this artifact a mistaken upload? `zos_management.zip`

### ISSUE THREAD

**Issue by ddimatos** [IBM/z_ansible_collections_samples#105]
I noticed this zip file, unsure of its purpose or need. Can you either explain or delete it its not needed.
https://github.com/IBM/z_ansible_collections_samples/commits/master/zos_management.zip

**Comment by zosmf-Robyn** [comment]
PR #106 is opened to delete this zip file.

**Comment by itsBryantP** [comment]
PR merged.
