### ISSUE TITLE
Broken links in z_ansible_collections_samples/zos_basics/constructs/

### ISSUE THREAD

**Issue by NayerNajafi** [IBM/z_ansible_collections_samples#138]
**Describe the bug**
I am not able to access doc links in https://github.com/IBM/z_ansible_collections_samples/tree/master/zos_basics/constructs.
**To Reproduce**
1. Go to https://github.com/IBM/z_ansible_collections_samples/tree/master/zos_basics/constructs
2. Click on "Review inventory documentation" and "Review host_vars documentation"
3. you will get 404

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jennyhuang17** [comment]
@NayerNajafi sorry about the delay. the two broken doc links are fixed
