### ISSUE TITLE
Firewall stop the podman 

### ISSUE THREAD

**Issue by juniororange** [IBM/z_ansible_collections_samples#193]
Env:  Local registry and bastion in one server

1. start a local registry by podman 
2. install the ansible scripts to install the openshift 
3.  Install  the bastion .
In this step firewall will be restart and stop my registry.  Need to stop the firewall and restart registry container.

**Comment by ddimatos** [comment]
@juniororange - please identify the playbook that has the issue, this is authored in such a way I can't understand if its an issue or a request to enhance. It looks to be related to the [Installing Red Hat OpenShift Container Platform](https://github.com/IBM/z_ansible_collections_samples/blob/main/z_infra_provisioning/cloud_infra_center/ocp_upi/README.md) playbook.

**Comment by ddimatos** [comment]
Closing because there seems to be no updates to this issue, feel free to reopen.
