### ISSUE TITLE
Problems with zos_copy module

### ISSUE THREAD

**Issue by rinaldou** [IBM/z_ansible_collections_samples#247]
**Describe the bug**
Trying to copy a local file (linux) to an existing PDS. It always says that the PDS already exists and fail

**To Reproduce**
Send the playbook below.

- hosts: zos
  collections:
    - ibm.ibm_zos_core
  gather_facts: yes
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
    job_name: "HELLO"
    environment_vars:
      _BPXK_AUTOCVT: "ON"
      PYTHONHOME: "/usr/lpp/PRODUTOS/python/v3r9/pyz"
      ZOAU_HOME: "/usr/lpp/PRODUTOS/zoau/v1r1"
      PYTHONPATH: "/usr/lpp/PRODUTOS/zoau/v1r1/lib"
      LIBPATH: "/lib:/usr/lpp/internet/bin:/usr/lpp/ctg/bin:/usr/lib:.:/usr/lpp/PRODUTOS/python/v3r9/pyz/lib:/usr/lpp/PRODUTOS/zoau/v1r1/lib"
      PATH: "/usr/lpp/java/J8.0_64/bin:/bin:/serpro/bin:/usr/lpp/PRODUTOS/python/v3r9/pyz/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin"
      _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
      _TAG_REDIR_ERR: "txt"
      _TAG_REDIR_IN: "txt"
      _TAG_REDIR_OUT: "txt"
      LANG: "C"
      PYTHONSTDINENCODING: "cp1047"
  remote_user: su09849
  environment: "{{ environment_vars }}"

  tasks:
    - name: Copy a local file to a USS
      zos_copy:
        src: /root/teste
        dest: K4160.SU09849.JCLLIB(AKIO)

**Expected behavior**
Copy the local file into the PDS

**Screenshots**
Output of the playbook.

ansible-playbook [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/pipx/venvs/ansible/lib64/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.18 (main, Sep 22 2023, 18:01:13) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/opt/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /usr/local/share/ansible/zos/hosts as it did not pass its verify_file() method
script declined parsing /usr/local/share/ansible/zos/hosts as it did not pass its verify_file() method
auto declined parsing /usr/local/share/ansible/zos/hosts as it did not pass its verify_file() method
Parsed /usr/local/share/ansible/zos/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: copyfile.yaml ********************************************************
1 plays in copyfile.yaml

PLAY [zos] *********************************************************************

TASK [Gathering Facts] *********************************************************
task path: /usr/local/share/ansible/zos/copyfile.yaml:1
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'echo ~su09849 && sleep 0'"'"''
<10.X.Y.Z> (Tste)
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /u/su09849/.ansible/tmp `"&& mkdir "` echo /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919 `" && echo ansible-tmp-1709731840.5816197-1229699-139327684213919="` echo /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919 `" ) && sleep 0'"'"''
<10.X.Y.Z> (0, b'ansible-tmp-1709731840.5816197-1229699-139327684213919=/u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919\n', b'')
<zostcpip02> Attempting python interpreter discovery
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'python3.11'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.10'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.9'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.8'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<10.X.Y.Z> (0, b'PLATFORM\nOS/390\nFOUND\n/usr/bin/python\nENDFOUND\n', b'')
<zostcpip02> Python interpreter discovery fallback (unsupported platform for extended discovery: os/390)
Using module file /opt/pipx/venvs/ansible/lib64/python3.9/site-packages/ansible/modules/setup.py
<10.X.Y.Z> PUT /root/.ansible/tmp/ansible-local-1229695jhoginjs/tmp9x8irsaa TO /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919/AnsiballZ_setup.py
<10.X.Y.Z> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' '[10.X.Y.Z]'
<10.X.Y.Z> (0, b'sftp> put /root/.ansible/tmp/ansible-local-1229695jhoginjs/tmp9x8irsaa /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919/AnsiballZ_setup.py\n', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'chmod u+x /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919/ /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919/AnsiballZ_setup.py && sleep 0'"'"''
<10.X.Y.Z> (0, b'', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' -tt 10.X.Y.Z '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON PYTHONHOME=/usr/lpp/PRODUTOS/python/v3r9/pyz ZOAU_HOME=/usr/lpp/PRODUTOS/zoau/v1r1 PYTHONPATH=/usr/lpp/PRODUTOS/zoau/v1r1/lib LIBPATH=/lib:/usr/lpp/internet/bin:/usr/lpp/ctg/bin:/usr/lib:.:/usr/lpp/PRODUTOS/python/v3r9/pyz/lib:/usr/lpp/PRODUTOS/zoau/v1r1/lib PATH=/usr/lpp/java/J8.0_64/bin:/bin:/serpro/bin:/usr/lpp/PRODUTOS/python/v3r9/pyz/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C PYTHONSTDINENCODING=cp1047 /usr/bin/python /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919/AnsiballZ_setup.py && sleep 0'"'"''
<10.X.Y.Z> (0, b'AttributeError("module \'os\' has no attribute \'getloadavg\'")\r\nValueError("invalid literal for int() with base 10: \'%s\'")\r\n\r\n{"ansible_facts": {"ansible_is_chroot": true, "ansible_virtualization_type": "", "ansible_virtualization_role": "", "ansible_virtualization_tech_guest": [], "ansible_virtualization_tech_host": [], "ansible_user_id": "SU09849", "ansible_user_uid": 21098492, "ansible_user_gid": 4190, "ansible_user_gecos": "", "ansible_user_dir": "/u/su09849", "ansible_user_shell": "/bin/sh", "ansible_real_user_id": 21098492, "ansible_effective_user_id": 21098492, "ansible_real_group_id": 4190, "ansible_effective_group_id": 4190, "ansible_system": "OS/390", "ansible_kernel": "29.00", "ansible_kernel_version": "05", "ansible_machine": "3931", "ansible_python_version": "3.9.2", "ansible_fqdn": "ZOSETCPIP02.SPO.SERPRO", "ansible_hostname": "KMEE", "ansible_nodename": "KMEE", "ansible_domain": "SPO.SERPRO", "ansible_userspace_bits": "64", "ansible_architecture": "3931", "ansible_distribution": "OS/390", "ansible_distribution_release": "29.00", "ansible_distribution_version": "05", "ansible_os_family": "OS/390", "ansible_local": {}, "ansible_lsb": {}, "ansible_selinux": {"status": "Missing selinux Python library"}, "ansible_selinux_python_present": false, "ansible_python": {"version": {"major": 3, "minor": 9, "micro": 2, "releaselevel": "final", "serial": 0}, "version_info": [3, 9, 2, "final", 0], "executable": "/usr/bin/python", "has_sslcontext": true, "type": "cpython"}, "ansible_fibre_channel_wwn": [], "ansible_system_capabilities_enforced": "N/A", "ansible_system_capabilities": "N/A", "ansible_dns": {}, "ansible_hostnqn": "", "ansible_apparmor": {"status": "disabled"}, "ansible_env": {"MAIL": "/usr/mail/SU09849", "PATH": "/usr/lpp/java/J8.0_64/bin:/bin:/serpro/bin:/usr/lpp/PRODUTOS/python/v3r9/pyz/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin", "_TAG_REDIR_IN": "txt", "SSH_CLIENT": "10.30.93.61 46632 22", "_BPXK_AUTOCVT": "ON", "SHELL": "/bin/sh", "SSH_TTY": "/dev/ttyp0000", "ZOAU_HOME": "/usr/lpp/PRODUTOS/zoau/v1r1", "_CEE_RUNOPTS": "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)", "PYTHONHOME": "/usr/lpp/PRODUTOS/python/v3r9/pyz", "_": "/usr/bin/python", "LOGNAME": "SU09849", "LANG": "C", "LIBPATH": "/usr/bin:/usr/lib:/lib:/usr/lpp/internet/bin:/usr/lpp/ctg/bin:/usr/lib:.:/usr/lpp/PRODUTOS/python/v3r9/pyz/lib:/usr/lpp/PRODUTOS/zoau/v1r1/lib", "_TAG_REDIR_OUT": "txt", "USER": "SU09849", "TERM": "xterm-256color", "HOME": "/u/su09849", "PYTHONSTDINENCODING": "cp1047", "PYTHONPATH": "/usr/lpp/PRODUTOS/zoau/v1r1/lib", "SSH_CONNECTION": "10.30.93.61 46632 10.X.Y.Z 22", "TZ": "BRT3", "_TAG_REDIR_ERR": "txt", "_EDC_SIG_DFLT": "1"}, "ansible_iscsi_iqn": "", "ansible_fips": false, "ansible_pkg_mgr": "unknown", "ansible_service_mgr": "service", "gather_subset": ["all"], "module_setup": true}, "invocation": {"module_args": {"gather_subset": ["all"], "gather_timeout": 10, "filter": [], "fact_path": "/etc/ansible/facts.d"}}}\r\n', b'Shared connection to 10.X.Y.Z closed.\r\n')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'rm -f -r /u/su09849/.ansible/tmp/ansible-tmp-1709731840.5816197-1229699-139327684213919/ > /dev/null 2>&1 && sleep 0'"'"''
<10.X.Y.Z> (0, b'', b'')
ok: [zostcpip02]

TASK [Copy a local file to a USS] **********************************************
task path: /usr/local/share/ansible/zos/copyfile.yaml:28
<10.X.Y.Z> ibm_zos_copy calculated size: 147
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' -tt 10.X.Y.Z 'mkdir -p /tmp/ansible-zos-copy-payload-D240306-T103041/teste'
<10.X.Y.Z> (0, b'', b'Shared connection to 10.X.Y.Z closed.\r\n')
<10.X.Y.Z> ibm_zos_copy SSH transfer method updated from None to sftp.
<10.X.Y.Z> ibm_zos_copy: put -r /root/teste TO /tmp/ansible-zos-copy-payload-D240306-T103041
<10.X.Y.Z> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' '[10.X.Y.Z]'
<10.X.Y.Z> (0, b'sftp> put -r /root/teste /tmp/ansible-zos-copy-payload-D240306-T103041\nEntering /root/teste/\n', b'')
<10.X.Y.Z> ibm_zos_copy return code: 0
<10.X.Y.Z> ibm_zos_copy stdout: b'sftp> put -r /root/teste /tmp/ansible-zos-copy-payload-D240306-T103041\nEntering /root/teste/\n'
<10.X.Y.Z> ibm_zos_copy stderr: b''
<10.X.Y.Z> play context verbosity: 3
<10.X.Y.Z> ibm_zos_copy SSH transfer method restored to None
<10.X.Y.Z> ibm_zos_copy temp path: /tmp/ansible-zos-copy-payload-D240306-T103041
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'echo ~su09849 && sleep 0'"'"''
<10.X.Y.Z> (0, b'/u/su09849\n', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /u/su09849/.ansible/tmp `"&& mkdir "` echo /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780 `" && echo ansible-tmp-1709731841.81896-1229715-201609309095780="` echo /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780 `" ) && sleep 0'"'"''
<10.X.Y.Z> (0, b'ansible-tmp-1709731841.81896-1229715-201609309095780=/u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780\n', b'')
Using module file /root/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.py
<10.X.Y.Z> PUT /root/.ansible/tmp/ansible-local-1229695jhoginjs/tmp_ylzd71v TO /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_copy.py
<10.X.Y.Z> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' '[10.X.Y.Z]'
<10.X.Y.Z> (0, b'sftp> put /root/.ansible/tmp/ansible-local-1229695jhoginjs/tmp_ylzd71v /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_copy.py\n', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'chmod u+x /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/ /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_copy.py && sleep 0'"'"''
<10.X.Y.Z> (0, b'', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' -tt 10.X.Y.Z '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON PYTHONHOME=/usr/lpp/PRODUTOS/python/v3r9/pyz ZOAU_HOME=/usr/lpp/PRODUTOS/zoau/v1r1 PYTHONPATH=/usr/lpp/PRODUTOS/zoau/v1r1/lib LIBPATH=/lib:/usr/lpp/internet/bin:/usr/lpp/ctg/bin:/usr/lib:.:/usr/lpp/PRODUTOS/python/v3r9/pyz/lib:/usr/lpp/PRODUTOS/zoau/v1r1/lib PATH=/usr/lpp/java/J8.0_64/bin:/bin:/serpro/bin:/usr/lpp/PRODUTOS/python/v3r9/pyz/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C PYTHONSTDINENCODING=cp1047 /usr/bin/python /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_copy.py && sleep 0'"'"''
<10.X.Y.Z> (1, b'\r\n{"dest_exists": false, "failed": true, "msg": "Unable to allocate destination data set: An error occurred during creation of data set \\"K4160.SU09849.JCLLIB\\". RC=4, BGYSC1409E Dataset K4160.SU09849.JCLLIB already exists. New dataset not allocated.\\n", "exception": "  File \\"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_cvhgtqwr/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.py\\", line 2937, in run_module\\n  File \\"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_cvhgtqwr/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_copy.py\\", line 2478, in allocate_destination_data_set\\n  File \\"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_cvhgtqwr/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py\\", line 180, in ensure_present\\n    DataSet.create(**arguments)\\n  File \\"/tmp/ansible_ibm.ibm_zos_core.zos_copy_payload_cvhgtqwr/ansible_ibm.ibm_zos_core.zos_copy_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py\\", line 1012, in create\\n    raise DatasetCreateError(\\n", "invocation": {"module_args": {"src": "/root/teste", "dest": "K4160.SU09849.JCLLIB(AKIO)", "size": 24046, "is_uss": false, "is_pds": false, "is_src_dir": true, "copy_member": true, "src_member": false, "temp_path": "/tmp/ansible-zos-copy-payload-D240306-T103041", "is_mvs_dest": false, "local_charset": "UTF-8", "is_binary": false, "executable": false, "asa_text": false, "aliases": false, "backup": false, "local_follow": true, "remote_src": false, "ignore_sftp_stderr": false, "validate": false, "use_template": false, "force": false, "force_lock": false, "unsafe_writes": false, "encoding": {"from": "UTF-8", "to": "IBM-1047"}, "content": null, "backup_name": null, "volume": null, "dest_data_set": null, "template_parameters": null, "mode": null, "tmp_hlq": null, "owner": null, "group": null, "seuser": null, "serole": null, "selevel": null, "setype": null, "attributes": null, "from_encoding": "UTF-8", "to_encoding": "IBM-1047"}}}\r\n', b'Shared connection to 10.X.Y.Z closed.\r\n')
<10.X.Y.Z> Failed to connect to the host via ssh: Shared connection to 10.X.Y.Z closed.
Using module file /root/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py
<10.X.Y.Z> PUT /root/.ansible/tmp/ansible-local-1229695jhoginjs/tmpaymjca5h TO /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_data_set.py
<10.X.Y.Z> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' '[10.X.Y.Z]'
<10.X.Y.Z> (0, b'sftp> put /root/.ansible/tmp/ansible-local-1229695jhoginjs/tmpaymjca5h /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_data_set.py\n', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'chmod u+x /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/ /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_data_set.py && sleep 0'"'"''
<10.X.Y.Z> (0, b'', b'')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' -tt 10.X.Y.Z '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON PYTHONHOME=/usr/lpp/PRODUTOS/python/v3r9/pyz ZOAU_HOME=/usr/lpp/PRODUTOS/zoau/v1r1 PYTHONPATH=/usr/lpp/PRODUTOS/zoau/v1r1/lib LIBPATH=/lib:/usr/lpp/internet/bin:/usr/lpp/ctg/bin:/usr/lib:.:/usr/lpp/PRODUTOS/python/v3r9/pyz/lib:/usr/lpp/PRODUTOS/zoau/v1r1/lib PATH=/usr/lpp/java/J8.0_64/bin:/bin:/serpro/bin:/usr/lpp/PRODUTOS/python/v3r9/pyz/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin:/usr/lpp/PRODUTOS/zoau/v1r1/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C PYTHONSTDINENCODING=cp1047 /usr/bin/python /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/AnsiballZ_zos_data_set.py && sleep 0'"'"''
<10.X.Y.Z> (0, b'\r\n{"changed": false, "message": "", "names": ["K4160.SU09849.JCLLIB(AKIO)"], "invocation": {"module_args": {"name": "K4160.SU09849.JCLLIB(AKIO)", "state": "absent", "type": "MEMBER", "space_type": "M", "space_primary": 5, "space_secondary": 3, "record_format": "FB", "replace": false, "force": false, "batch": null, "sms_management_class": null, "sms_storage_class": null, "sms_data_class": null, "block_size": null, "directory_blocks": null, "record_length": null, "key_offset": null, "key_length": null, "volumes": null, "tmp_hlq": null}}}\r\n', b'Shared connection to 10.X.Y.Z closed.\r\n')
<10.X.Y.Z> ESTABLISH SSH CONNECTION FOR USER: su09849
<10.X.Y.Z> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/root/.ssh/akio-private.crt"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="su09849"' -o ConnectTimeout=10 -o 'ControlPath="/root/.ansible/cp/b6c1c482e8"' 10.X.Y.Z '/bin/sh -c '"'"'rm -f -r /u/su09849/.ansible/tmp/ansible-tmp-1709731841.81896-1229715-201609309095780/ > /dev/null 2>&1 && sleep 0'"'"''
<10.X.Y.Z> (0, b'', b'')
fatal: [zostcpip02]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dest": "K4160.SU09849.JCLLIB(AKIO)",
            "src": "/root/teste"
        }
    },
    "msg": "Unable to allocate destination data set: An error occurred during creation of data set \"K4160.SU09849.JCLLIB\". RC=4, BGYSC1409E Dataset K4160.SU09849.JCLLIB already exists. New dataset not allocated.\n",
    "rc": null,
    "stderr": null,
    "stderr_lines": null,
    "stdout": null,
    "stdout_lines": null
}

PLAY RECAP *********************************************************************
zostcpip02                 : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Additional context**

**Comment by ddimatos** [comment]
@rinaldou this repository is monitored by the playbook contributors, I happen to notice this issue and you are reporting against the ibm_zos_core collection, please open a git issue or discussion in that projects repository, if this is still an issue. 
https://github.com/ansible-collections/ibm_zos_core
