### ISSUE TITLE
CEE3501S The module libpython3.6m.so was not found with IBM open entreprise python

### ISSUE THREAD

**Issue by philippe-richard** [IBM/z_ansible_collections_samples#30]
i am using
 IBM Open Enterprise Python for z/OS — Installed and configured on USS environment  via the download
PRICHAR@X9:/u/prichar #python3 --version   
Python 3.8.6                               

IBM Z Open Automation Utilities (ZOAU) — Installed and configured on USS environment (version 1.0.0) via the download

On the linux (windows WSL) i have:
 ansible-galaxy --version
ansible-galaxy 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/prichar/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-galaxy
  python version = 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0]

ansible zos core collection 1.2.0
 "namespace": "ibm",
  "version": "1.2.0",

When i run a sample playbook which invokes zos create dataset, like:
    - name: Create a sequential data set
      zos_data_set:
        name: "{{ data_set_name }}"
        type: seq
        state: present
        record_length: 80
        format: fb
        space_type: TRK
        space_primary: 5
      register: result

then i get the following error:

[TASK [Create a sequential data set] ************************************************************************************
task path: /home/prichar/ansible/root-ansible/ibm_zos_core/playbooks/dataset_basics.yaml:118
Using module file /home/prichar/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py
Pipelining is enabled.
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/home/prichar/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/home/prichar/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON ZOAU_HOME=/usr/lpp/IBM/zoautil ZOAU_ROOT=/usr/lpp/IBM/zoautil PYTHONPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz:/lib:/usr/lib LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. PATH=/usr/lpp/IBM/zoautil/bin:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C tgt_tmp_dir=/tmp ctl_tmp_dir=/tmp /usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3 && sleep 0'"'"''
<9.212.128.238> (137, b'', b'CEE3501S The module libpython3.6m.so was not found.\n         From compile unit TOROLABA:./Python/dynload_shlib.c at entry point _PyImport_FindSharedFuncptr at statement 99 at compile unit offset +0000000024A05DE0 at entry offset +0000000000000290 at address 0000000024A05DE0.\n')
<9.212.128.238> Failed to connect to the host via ssh: CEE3501S The module libpython3.6m.so was not found.
         From compile unit TOROLABA:./Python/dynload_shlib.c at entry point _PyImport_FindSharedFuncptr at statement 99 at compile unit offset +0000000024A05DE0 at entry offset +0000000000000290 at address 0000000024A05DE0.
fatal: [zvm]: FAILED! => {
    "changed": false,
    "module_stderr": "CEE3501S The module libpython3.6m.so was not found.\n         From compile unit TOROLABA:./Python/dynload_shlib.c at entry point _PyImport_FindSharedFuncptr at statement 99 at compile unit offset +0000000024A05DE0 at entry offset +0000000000000290 at address 0000000024A05DE0.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 137
}

PLAY RECAP *************************************************************************************************************
zvm                        : ok=7    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0](url)

libpython3.6m.so  is a module shipped by rocket python, but not IBM open entreprise Python. I have no idea why it needs this module.
My version of python ( IBM open entreprise Python) is installed at:
/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/bin

**Comment by ddimatos** [comment]
My apologies this go overlooked, it was close to the holidays and then a busy Q1.

From what i can see your environment variables are adding more than what is needed, if this is still an issue please post them along with your inventory.

I see in your `PYTHONPATH` you have:
   PYTHONPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz:/lib:/usr/lib 
You only need:
  PYTHONPATH=/usr/lpp/IBM/zoautil/lib
  
Configuring `PYZ` & `ZOAU` here would correctly populate `PYTHONPATH`, no need to add more as it appears. 
  
PYZ: "/usr/lpp/IBM/cyp/v3r8/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/sbin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  
  If this is still an unresolved issue please share the environment variables and inventory.

**Comment by ddimatos** [comment]
Feel free to change the status and reopen if this issue continues to persist.
