### ISSUE TITLE
ZOAU is not properly configured for Ansible. Unable to import zoautil_py. Ensure environment variables are properly configured in Ansible for use with ZOAU

### ISSUE THREAD

**Issue by philippe-richard** [IBM/z_ansible_collections_samples#31]
When i configure ZOAU 1.1.0 (installed from the download), i get a different error message than with ZOAU 1.0 (as reported in issue #30 ):

[TASK [Create a sequential data set] ************************************************************************************
task path: /home/prichar/ansible/root-ansible/ibm_zos_core/playbooks/dataset_basics.yaml:118
Using module file /home/prichar/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py
Pipelining is enabled.
<9.212.128.238> ESTABLISH SSH CONNECTION FOR USER: prichar
<9.212.128.238> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o 'IdentityFile="/home/prichar/.ssh/mykey"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="prichar"' -o ConnectTimeout=10 -o ControlPath=/home/prichar/.ansible/cp/4356cca0a9 9.212.128.238 '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON ZOAU_HOME=/usr/lpp/IBM/zoautil ZOAU_ROOT=/usr/lpp/IBM/zoautil PYTHONPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz:/lib:/usr/lib LIBPATH=/usr/lpp/IBM/zoautil/lib:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. PATH=/usr/lpp/IBM/zoautil/bin:/usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C tgt_tmp_dir=/tmp ctl_tmp_dir=/tmp /usr/local/rocket/py38/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3 && sleep 0'"'"''
<9.212.128.238> (1, b'\n{"msg": "ImportError(\'ZOAU is not properly configured for Ansible. Unable to import zoautil_py. Ensure environment variables are properly configured in Ansible for use with ZOAU.\')", "changed": false, "message": "", "names": ["PRICHAR.P0065576.T0513642.C0000000"], "failed": true, "exception": "  File \\"/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py\\", line 1166, in run_module\\n  File \\"/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py\\", line 893, in perform_data_set_operations\\n  File \\"/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py\\", line 170, in ensure_present\\n    DataSet.create(**arguments)\\n  File \\"/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py\\", line 543, in create\\n    rc = Datasets.create(**formatted_args)\\n  File \\"/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/import_handler.py\\", line 12, in method\\n    raise ImportError(\\n", "invocation": {"module_args": {"name": "PRICHAR.P0065576.T0513642.C0000000", "type": "seq", "state": "present", "record_length": 80, "format": "fb", "space_type": "TRK", "space_primary": 5, "record_format": "fb", "replace": false, "batch": null, "space_secondary": null, "sms_management_class": null, "sms_storage_class": null, "sms_data_class": null, "block_size": null, "directory_blocks": null, "key_offset": null, "key_length": null, "volumes": null}}}\n', b'')
<9.212.128.238> Failed to connect to the host via ssh:
The full traceback is:
  File "/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py", line 1166, in run_module
  File "/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py", line 893, in perform_data_set_operations
  File "/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py", line 170, in ensure_present
    DataSet.create(**arguments)
  File "/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py", line 543, in create
    rc = Datasets.create(**formatted_args)
  File "/tmp/ansible_zos_data_set_payload_wwdqxeon/ansible_zos_data_set_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/import_handler.py", line 12, in method
    raise ImportError(
fatal: [zvm]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "batch": null,
            "block_size": null,
            "directory_blocks": null,
            "format": "fb",
            "key_length": null,
            "key_offset": null,
            "name": "PRICHAR.P0065576.T0513642.C0000000",
            "record_format": "fb",
            "record_length": 80,
            "replace": false,
            "sms_data_class": null,
            "sms_management_class": null,
            "sms_storage_class": null,
            "space_primary": 5,
            "space_secondary": null,
            "space_type": "TRK",
            "state": "present",
            "type": "seq",
            "volumes": null
        }
    },
    "message": "",
    "msg": "ImportError('ZOAU is not properly configured for Ansible. Unable to import zoautil_py. Ensure environment variables are properly configured in Ansible for use with ZOAU.')",
    "names": [
        "PRICHAR.P0065576.T0513642.C0000000"
    ]
}
](url)

**Comment by philippe-richard** [comment]
when i compare the 2 installations of ZOAU (1.0.0 and 1.1.0), i see that there are some differences:

in 1.0.0 i see:
EUID=0   /X9/tmp/zoautil/lib/                                                  
  Type  Perm  Changed-GMT-1     Owner      ------Size  Filename    Row 1 of 9  
_ Dir    755  2020-03-09 10:25  ROOT             8192  ..                      
_ Dir    755  2020-01-20 23:52  ROOT             8192  .                       
_ Dir    755  2020-01-20 23:48  ROOT             8192  zoautil_py              
_ File   755  2020-01-20 23:45  ROOT           143360  libZOAU_JNI64.so        
_ File   755  2020-01-20 23:45  ROOT            72760  com.ibm.zoautil_1.0.1.ja
_ File   755  2020-01-20 23:45  ROOT          1674456  log4j-core-2.12.1.jar   
_ File   755  2020-01-20 23:45  ROOT           276769  log4j-api-2.12.1.jar    
_ File   755  2020-01-20 23:38  ROOT              240  zoautil.x               
_ File   755  2020-01-20 23:38  ROOT           106496  zoautil.so              


in 1.1.0 i see no zoautil_py
Select one or more files with / or action codes.                               
EUID=0   /Z24R01/usr/lpp/IBM/zoautil/lib/                                      
  Type  Perm  Changed-GMT-1     Owner      ------Size  Filename    Row 1 of 8  
_ Dir    755  2020-12-17 12:07  ROOT             8192  ..                      
_ Dir    755  2020-09-25 15:33  ROLECEO          8192  .                       
_ File   775  2020-09-25 15:23  ROLECEO        147456  libZOAU_JNI64.so        
_ File   644  2020-09-25 15:23  ROLECEO         78821  com.ibm.zoautil_1.1.0.ja
_ File   644  2020-09-25 15:23  ROLECEO       1674456  log4j-core-2.12.1.jar   
_ File   644  2020-09-25 15:23  ROLECEO        276769  log4j-api-2.12.1.jar    
_ File   644  2020-09-25 15:06  ROLECEO           320  zoautil.x               
_ File   755  2020-09-25 15:06  ROLECEO        135168  zoautil.so      

Is this normal ?

**Comment by philippe-richard** [comment]
i tried a sample python program on USS, containing :
#Import the Z Open Automation Utilities libraries we need        
from zoautil_py import MVSCmd, Datasets                          
from zoautil_py.types import DDStatement                         
# Import datetime, needed so we can format the report            
from datetime import datetime                                    
# Import os, needed to get the environment variables             
import os                                                        
#Take the contents of this data set and read it into cc_contents 
and when i invoke it with python3 zoatest.py, i get
PRICHAR@X9:/u/prichar #python3 zoatest.py                                     
Traceback (most recent call last):                                            
  File "zoatest.py", line 2, in <module>                                      
    from zoautil_py import MVSCmd, Datasets                                   
ImportError: cannot import name 'MVSCmd' from 'zoautil_py' (unknown location) 

So my question is: is zoautil_py supposed to be shipped with ZOAU 1.1.0, like it was in ZOAU 1.0.0 ? am i missing any additional customization step ?

**Comment by philippe-richard** [comment]
note: I have also installed the ZOAU Python libraries on the z/OS target for use by z/OS Ansible core and other collections with:
 
`PRICHAR@X9:/Z24R01/usr/lpp/IBM/zoautil #pip3 install zoautil_py-1.1.0.tar.gz    
Processing ./zoautil_py-1.1.0.tar.gz                                            
-Ý33mDEPRECATION: Source distribution is being reinstalled despite an installed 
package having the same name and version as the installed package. pip 21.1 will
 remove support for this functionality. A possible replacement is use --force-re
install. You can find discussion regarding this at https://github.com/pypa/pip/i
ssues/8711.-Ý0m                                                                 
Using legacy 'setup.py install' for zoautil-py, since package 'wheel' is not ins
talled.                                                                         
Installing collected packages: zoautil-py                                       
  Attempting uninstall: zoautil-py                                              
    Found existing installation: zoautil-py 1.1.0                               
    Uninstalling zoautil-py-1.1.0:                                              
      Successfully uninstalled zoautil-py-1.1.0                                 
    Running setup.py install for zoautil-py ... -Ý?25ldone                      
-Ý?25hSuccessfully installed zoautil-py-1.1.0                                   
PRICHAR@X9:/Z24R01/usr/lpp/IBM/zoautil #ls lib                                  
com.ibm.zoautil_1.1.0.jar  log4j-api-2.12.1.jar       zoautil.so                
libZOAU_JNI64.so           log4j-core-2.12.1.jar      zoautil.x                 
`
so i see no change in the ZOAU filesystem /lib

**Comment by ryanp54** [comment]
@philippe-richard 
I am getting this same error, but I only get it when I am using the 1.3.0-beta.1 of the ibm_zos_core collection. It does not occur if I use the 1.2.1 release. I am going to try to investigate the difference that is leading to this. I'll let you know if I find anything.

**Comment by adn1107** [comment]
from what i know:

use ibm_zos_core 1.2.x release with ZOAU 1.0.x
use ibm_zos_core 1.3.x release with ZOAU 1.1.x

**Comment by ryanp54** [comment]
Ah ok, that's my issue then.

**Comment by willmvs** [comment]
@philippe-richard I was facing the same issue and upgrading to ibm_zos_core 1.3.0-beta.1 solved it. You can do it with the command:
`ansible-galaxy collection install ibm.ibm_zos_core:1.3.0-beta.1 --force`

Like adn1107 mentioned I found the release notes for ibm_zos_core also cover the supported versions:
https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html

**Comment by ddimatos** [comment]
For the record you can view your pip installed libraries with the below command and env vars (set vars according to your system):

```
   export LIBPATH=/products/python/v3r8/pyz/lib
   export _BPXK_AUTOCVT='ON'
   export _CEE_RUNOPTS='FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'
   export PATH=/products/python/v3r8/pyz/bin:$PATH
   
   pip3.8 freeze
   ```
   
With the default PIP installation command `pip3 install zoautil_py-1.1.0.tar.gz` of `zoautil_py` it will install the python libs under your  /<python_install_path>/site-packages, not under where ZOAU is installed. 

In ZOAU 1.1.0, python libraries were included because they compile during installation and better represent the customers environment over a precompiled binary. In the future there will likely a choice of PIP or pre-compiled. 

In February updates were made to host_setup.yaml to support ZOAU 1.1.0, future proof it and cases where there is more than one ZOAU installed. You can review that here: https://github.com/IBM/z_ansible_collections_samples/pull/34

Last resort, should you not be able to execute `host_setup.yaml` you can fall back to the detailed installation instructions, its more verbose than it is complex, you can find that here:
https://github.com/IBM/z_ansible_collections_samples/blob/master/docs/share/configuration_guide.md

**Comment by ddimatos** [comment]
Feel free to change the status and reopen if this issue continues to persist.
