### ISSUE TITLE
Wrong playbook extension in some sample commands on README.md

### ISSUE THREAD

**Issue by willmvs** [IBM/z_ansible_collections_samples#44]
First of all, I would like to thank you all for gathering and sharing these samples, they helped me a lot in learning Ansible and learning how to use it for z/OS systems.

This is really minor but I thought I would mention as it might help other new users like me. 
After cloning the repository and trying the samples, at some point I faced an error message like:
`ERROR! the playbook: zos_operator_basics.yml could not be found
`

Initially I thought I was making some newbie mistake, but then I noticed the sample command that I copied from the README.md had the wrong extension for the playbook file. 
For example, if we check zos_concepts/zos_operator/zos_operator_basics the sample command from the "Run desired playbook" section is:
`ansible-playbook -i inventory.yml zos_operator_basics.yml
`
However the related playbook is using .yaml extension, zos_operator_basics.yaml , so the command fails with the not found message. The good part is that once the user figures it they can easily fix the command and move on.

So far I noticed this happens in these README.md :
zos_concepts/zos_operator/zos_operator_basics/
zos_concepts/encoding/convert_encoding/
zos_concepts/data_transfer/copy_fetch_data_set/
zos_concepts/data_sets/data_set_basics/

For the sample folders that contain multiple playbooks, the "Run desired playbook" section avoids this by saying:
`ansible-playbook -i inventory.yml <playbook-name>
`

So, I believe one easy option would be to update the README.md to fix the typo. But it might be worth considering to use `<playbook-name>` in all sample commands. Or maybe make all sample playbooks use .yml for consistency? (I'm not sure if there's a reason for some being .yaml and some .yml)

I would be glad to help with the updates once you decide what's best.

Thank you!

**Comment by ddimatos** [comment]
@willmvs - thank you for this and the time you took to explain the issue. This is helpful, I am planning a fairly large update to the readme's and the timing is good. I will probably handle that in the coming days. As for as constancy, I agree, there is no reason to be using both extensions and I am glad you found this collection useful, stay tuned as we add more :).

**Comment by ddimatos** [comment]
Thank you @willmvs for offering to help with the updates, at this time because of the large change in my latest PR, I went with updating the docs to use the correct extension. I do think the next round of updates should standardize on a choice of either `.yaml` or `.yml` to avoid such issues in the future. 

I would gladly accept help, it should be after the pull request merges. I will get back to you. Also, on another note, soon we will be allowing contributions to the repository so should you be inspired to contribute :) we would be happy to accept :)

**Comment by willmvs** [comment]
Thank you @ddimatos this is great to hear! I'll stay tuned :)

**Comment by ddimatos** [comment]
@willmvs - this is being addressed in [this pull request](https://github.com/IBM/z_ansible_collections_samples/pull/108) as part of a larger effort. Thank you for bring this up and your patience.
