### ISSUE TITLE
Broken link in CIC OCP UPI README.md

### ISSUE THREAD

**Issue by vmorris** [IBM/z_ansible_collections_samples#67]
This link to the known issues file is broken (the file does not exist in this repository).

https://github.com/IBM/z_ansible_collections_samples/blame/master/z_infra_provisioning/cloud_infra_center/ocp_upi/README.md#L45-L46

**Comment by ddimatos** [comment]
FYI:
@zhengxiaomei123 
@gyohuangxin

**Comment by gyohuangxin** [comment]
@vmorris Thank you. I've raised a PR to fix this.
